### ISSUE TITLE
Setup Github Pages w/ automated build

### ISSUE THREAD

**Issue by wildintellect** [developmentseed/scaling_science#2]
Following https://jupyterbook.org/en/stable/publish/gh-pages.html#github-pages-and-actions we should deploy the website updates automatically whenever PRs are merged to main.

Bonus if we want we can also enable preview builds on PRs.

For simplicity it sounds like @lillythomas wants to use a `gh-pages` branch. This can wait until after #1 is merged so there is content.

**Comment by lillythomas** [comment]
Closing as complete.
