### ISSUE TITLE
Review Python Dependencies

### ISSUE THREAD

**Issue by wildintellect** [developmentseed/scaling_science#7]
The notebooks/examples rely on python, but we don't execute the notebooks right now as part of the book build.
This leads to a few things:
1. ~Interactive visualizations may or may not load in the pages~
2. ~The dependencies need to be in a separate file ( done in #6 )~
3. We need to revisit the currency of the dependencies, aka outdated versions (e.g. pandas and xarray)
4. We need to decide if we're going to recommend Jupyter should we be recommending `conda` for env management?

**Comment by wildintellect** [comment]
We moved the dependencies back to the top level for Binder compatibility (repo2docker), but still need to revisit bringing the libraries up to date.

**Comment by lillythomas** [comment]
I think all is addressed here @wildintellect
